CREATE TABLE IF NOT EXISTS customers (
    id INT AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    total_points INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);